export const TICKET_ACTION_REQUEST = "TICKET_ACTION_REQUEST";
export const TICKET_ACTION_SUCCESS = "TICKET_ACTION_SUCCESS";
export const TICKET_ACTION_FAIL = "TICKET_ACTION_FAIL";
export const TICKET_ACTION_RESET = "TICKET_ACTION_RESET";

export const ACTION_TICKET_LIST_REQUEST = "ACTION_TICKET_LIST_REQUEST";
export const ACTION_TICKET_LIST_SUCCESS = "ACTION_TICKET_LIST_SUCCESS";
export const ACTION_TICKET_LIST_FAIL = "ACTION_TICKET_LIST_FAIL";
export const ACTION_TICKET_LIST_RESET = "ACTION_TICKET_LIST_RESET";
