export const TICKET_ACTION_REQUEST = "TICKET_ACTION_REQUEST";
export const TICKET_ACTION_SUCCESS = "TICKET_ACTION_SUCCESS";
export const TICKET_ACTION_FAIL = "TICKET_ACTION_FAIL";
export const TICKET_ACTION_RESET = "TICKET_ACTION_RESET";
