export const TICKET_LISTS_REQUEST = "TICKET_LISTS_REQUEST";
export const TICKET_LISTS_SUCCESS = "TICKET_LISTS_SUCCESS";
export const TICKET_LISTS_FAIL = "TICKET_LISTS_FAIL";
export const TICKET_LISTS_RESET = "TICKET_LISTS_RESET";
