export const TICKET_LISTS_REQUEST = "TICKET_LISTS_REQUEST";
export const TICKET_LISTS_SUCCESS = "TICKET_LISTS_SUCCESS";
export const TICKET_LISTS_FAIL = "TICKET_LISTS_FAIL";
export const TICKET_LISTS_RESET = "TICKET_LISTS_RESET";

export const SINGLE_TICKET_REQUEST = "SINGLE_TICKET_REQUEST";
export const SINGLE_TICKET_SUCCESS = "SINGLE_TICKET_SUCCESS";
export const SINGLE_TICKET_FAIL = "SINGLE_TICKET_FAIL";
