export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "UER_LOGINN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGINN_FAIL";
export const USER_LOGOUT = "USEER_LOGOUT";
